# Generated by Django 4.2.20 on 2025-03-11 05:16

import _base.files
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowfiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=_base.files.upload_to_generic)),
                ('initials', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='growfi_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='growfi_users_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowfiUserToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mf_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growfi_auth_token', to='users.growfiuser')),
            ],
            options={
                'verbose_name': '2. User Token',
                'ordering': ['-created'],
            },
        ),
    ]
