# Generated by Django 4.2.20 on 2025-03-11 05:20

import _base.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growfiusertoken',
            old_name='mf_user',
            new_name='growfi_user',
        ),
        migrations.AlterField(
            model_name='growfiuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=_base.files.upload_to_generic),
        ),
    ]
