# Generated by Django 4.2.20 on 2025-03-11 07:02

import _base.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mf_user_growfiusertoken_growfi_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growfiuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=_base.files.upload_to_generic),
        ),
    ]
