# Generated by Django 4.2.20 on 2025-03-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
